M48
; DRILL file {KiCad 7.0.8} date Mon Apr 29 01:09:04 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-29T01:09:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0390
%
G90
G05
T1
X3.175Y-0.8705
X3.175Y-1.098
T2
X3.1417Y-1.7717
T3
X3.1986Y-1.4551
X3.2386Y-1.6551
X3.2786Y-1.4551
T0
M30
